### ISSUE TITLE
RepeatCount count defaults to 1 even if you change the value.

### ISSUE THREAD

**Issue by oridotaoyebode** [sthewissen/Xamarin.Forms.EasyLoading#1]
`public LoadingLayoutController(Layout<View> layout, int repeatCount)
        {
            _layoutWeakReference = new WeakReference<Layout<View>>(layout);
            _repeatCount = 1;
        }`

**Comment by sthewissen** [comment]
Probably need to change that to:

```
public LoadingLayoutController(Layout<View> layout, int repeatCount) 
{
   _layoutWeakReference = new WeakReference<Layout<View>>(layout);
   _repeatCount = repeatCount <= 0 ? 1 : repeatCount;
}
```

**Comment by oridotaoyebode** [comment]
Hi. Yes. 

Also, I noticed if the parent is a Grid, the repeat count property is "kinda" ignored in the sense that it will only show one loading item. 

I have a hack that fixes the issue by first adding a StackLayout to the Grid, then adding the items to the StackLayout. 

Do you want a pull request or can I post code here?

**Comment by sthewissen** [comment]
Please try the 1.0.3-beta package and let me know if that fixes your problems.

**Comment by oridotaoyebode** [comment]
Will do

**Comment by oridotaoyebode** [comment]
@sthewissen works like a charm
